#! /bin/bash
#SBATCH -A see200002p
#SBATCH -p RM-shared
#SBATCH -J myjob
#SBATCH --mail-user=swetha@udel.edu
#SBATCH --mail-type=ALL

#SBATCH -N 1
#SBATCH -n 2
#SBATCH -t 00:05:00
export ACC_NUM_CORES=2
./mc_acc



